## 1.19. Решить следующие системы уравнений:

### 1.19.1*

\begin{align}
8x_1 - 5x_2 = 13 \\
3x_1 - 2x_2 = 10
\end{align}

In [13]:
import numpy as np
a = np.array([[8,-5], [3,-2]])
b = np.array([13,10])
x = np.linalg.solve(a, b)
x

array([-24., -41.])

### 1.19.2*

\begin{align}
x_1 + 8x_2 = 7 \\
-x_1 - 9x_2 = 8
\end{align}

In [14]:
a = np.array([[1,8], [-1,-9]])
b = np.array([7,8])
x = np.linalg.solve(a, b)
x

array([127., -15.])

### 1.19.3*

\begin{align}
9x_1 + 3x_2 = 6 \\
6x_1 + 2x_2 = 8
\end{align}

In [15]:
a = np.array([[9,3], [6,2]])
b = np.array([6,8])
x = np.linalg.solve(a, b)
x

LinAlgError: Singular matrix

### 1.19.4*

\begin{align}
2x_1 + 3x_2 = 12 \\
-5x_1 - 10x_2 = 8
\end{align}

In [16]:
import numpy as np
a = np.array([[2,3], [-5,-10]])
b = np.array([12,8])
x = np.linalg.solve(a, b)
x

array([ 28.8, -15.2])